### ISSUE TITLE
Adicionar atributo 'ehTemplate' em Prontuário

### ISSUE THREAD

**Issue by PauloVLB** [PauloVLB/DASH#25]
Foi visto que é necessário adicionar um atributo booleano no prontuário para verificar se ele aceita respostas ou não. 

Essa tarefa consiste em adicionar esse atributo (`ehTemplate : boolean`) na classe Prontuário e realizar as mudanças necessárias nas outras classes, quando necessário. 

Classes para verificar se há impacto pela mudança:
* ProntuarioRepository 
* ProntuarioService
* ProntuarioController
* ProntuarioMapper
* ProntuarioCreate
* ProntuarioUpdate
* ProntuarioOutput

Já foi adicionado o atributo no diagrama do projeto.

**Comment by DanteAugusto** [comment]
Um prontuário que foi cadastrado como não template pode ser atualizado para ser? Se sim, devo tratar de remover suas respostas nessa issue?

**Comment by PauloVLB** [comment]
Não. Uma vez criado como não-template, ele não pode ser atualizado para ser. 

Mais pra frente podemos adotar o padrão nas rotas com `/template`, talvez fique melhor. Exemplo: `POST /prontuario/template` (cria um template de prontuário, que não pode ter `ehTemplate` modificado).

**Comment by DanteAugusto** [comment]
Blz
