### ISSUE TITLE
CRUD e operacoes de Diagnostico

### ISSUE THREAD

**Issue by PauloVLB** [PauloVLB/DASH#52]
Issue parte de #35.

No CRUD básico da entidade, não precisa fazer o create, visto que eles sempre serão criados associados a um prontuário.

Além disso, serão necessários:
```
POST   /diagnostico/{id}/addOpcao
DELETE /diagnostico/{id}/removeOpcao

POST   /prontuario/{id}/addDiagnostico
DELETE /prontuario/{id}/removeDiagnostico
```

**Comment by DanteAugusto** [comment]
A associação com opções não ocorre na criação, né? Quando criado, associa somente ao prontuário.
